apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - knative-serving.yaml
  - cert-manager.yaml
  - cert-manager-config.yaml
  - knative-tls.yaml
  - crossplane.yaml
  - crossplane-providers.yaml
  - crossplane-config.yaml
  - local-path-provisioner.yaml
  - zitadel-postgres.yaml
  - zitadel.yaml
  - plattform-oauth2-app.yaml
  - registry.yaml
