apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: zitadel-postgres
  namespace: flux-system
spec:
  interval: 10m
  timeout: 10m
  retryInterval: 2m
  dependsOn:
    - name: local-path-provisioner
  path: ./infrastructure/zitadel-postgres
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: zitadel-postgresql
      namespace: zitadel
