apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrepository-jetstack.yaml
  - helmrepository-duckdns-webhook.yaml
  - helmrelease-cert-manager.yaml
  - helmrelease-duckdns-webhook.yaml
  - cluster-issuer.yaml
