apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: zitadel
spec:
  selector:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: zitadel-postgresql
    app.kubernetes.io/component: primary
  ports:
    - port: 5432
      targetPort: 5432
