apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zitadel
  namespace: flux-system
spec:
  interval: 1h
  chart:
    spec:
      chart: zitadel
      version: ">=7.0.0 <8.0.0"
      sourceRef:
        kind: HelmRepository
        name: zitadel
        namespace: flux-system
  targetNamespace: zitadel
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 0
      remediateLastFailure: true
      strategy: uninstall
  values:
    zitadel:
      masterkey: "MasterkeyNeedsToHave32Characters"
      configmapConfig:
        SystemAPIUsers:
          plattform-init:
            KeyData: |
              -----BEGIN PUBLIC KEY-----
              MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzpezQpr2S2SiiJma7DtA
              fWaxrfM5aXdhz5jRenkMkSr8hKAmjOXwH0B1IFpkvMSiKgNYBWscvBTmM7uXBt1A
              b6iCjZTRbJtkFoKXk+eDJibe7gJPG98CXI0AB/FS0XZElHOQMUIwLMF+Shw7eIQH
              joGzLlf91MLsLrZignAgiE2/N21EWVSc54YeVp+6OAL3SI/ocQfj8xVrpqvVoNUW
              59ubdj95TzDQuymk2iFKFb8tgymQwqknHHtTH6wYyQ/2Pr9ebBwFoqqfH6g6QQV7
              lKRXjx9R0jVRVo6TrJ1iqyf6WqyY+0xgChTmXho/mAHg/EluIubMIEKyGJ2hnfKe
              RwIDAQAB
              -----END PUBLIC KEY-----
        FirstInstance:
          Org:
            Name: ZITADEL
            Domain: auth.192.168.1.249.sslip.io
        ExternalDomain: auth.192.168.1.249.sslip.io
        ExternalPort: 443
        ExternalSecure: true
        TLS:
          Enabled: false
        Database:
          Postgres:
            Host: postgresql
            Port: 5432
            Database: zitadel
            MaxOpenConns: 20
            MaxIdleConns: 10
            ConnMaxLifetime: "30m"
            User:
              Username: zitadel
              SSL:
                Mode: disable
            Admin:
              Username: postgres
              SSL:
                Mode: disable
      secretConfig:
        Database:
          Postgres:
            User:
              Password: "zitadel123"
            Admin:
              Password: "postgres123"
    postgresql:
      enabled: false
    replicaCount: 1
