apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: walter
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: ghcr.io/paul-asvb/albrecht:latest
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
