apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: walter
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: registry.192.168.1.249.sslip.io/walter:latest
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
